{% set name = "epysurv" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jarnorfb/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 31752c32e09a0668bd2b6f0cc7672c41a19c149e664da652628fa7a33d25d8cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rpy2 <3
    - r-base
    - r-gamlss
    - r-gridbase
    - r-mglm
    - r-msm
    - r-surveillance
    - numpy >=1.14
    - matplotlib-base
    - pandas
    - scipy
    - seaborn
    - plotnine
    - tzlocal

test:
  imports:
    - epysurv
    - epysurv.models
    - epysurv.data
    - epysurv.visualization
    - epysurv.simulation
    - epysurv.metrics
  requires:
    - pytest
    - pytest-datadir
  source_files:
    - tests/
  commands:
    - pytest

about:
  home: https://github.com/JarnoRFB/epysurv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Epidemiological surveillance in Python

  description: |
    epysurv provides access to epidemiological surveillance in Python by
    wrapping the R surveillance package.
  dev_url: https://github.com/JarnoRFB/epysurv

extra:
  recipe-maintainers:
    - JarnoRFB
    - justinshenk
